### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by ukBaz** [96boards/96BoardsGPIO#7]
Hello,

I appear to be having issues using the Python bindings on the Dragonboard 410c. I'm getting the following message when importing the library in to Python:

```
OSError: lib96BoardsGPIO.so: cannot open shared object file: No such file or directory
```

The file does exist in /usr/local/lib

Is it possible that you could create a Python Package and put it on PyPi?

Thanks,
Barry

**Comment by doanac** [comment]
Hi Barry,

I've just committed a change that will fix this issue:

 https://github.com/96boards/96BoardsGPIO/commit/efeef24c29c8e690268f5bfe63f8646f7a8c4b90

I think this might be hard to manage on PyPi because it depends on libsoc so it would wind up having to build to shared libraries. That said - both libsoc and 96BoardsGPIO are about to be packaged and installed by default in upcoming 96Boards images. So I _think_ that will solve your core complaint in a different.

**Comment by ukBaz** [comment]
Hi Andy,

Thanks for the quick response on this. I'll test and let you know.

FYI: I did have LD_LIBRARY_PATH set and I was still seeing the error.

I agree my PyPi suggestion was really about lowering the barrier to users being able to explore the GPIO and so having the Python bindings installed by default does help considerably with that.

Regards,
Barry

**Comment by ukBaz** [comment]
Hello Andy,

I did a pull of the new code etc and I got a new error message of:

```
OSError: libsoc.so.2: cannot open shared object file: No such file or directory
```

despite having the following in my .bashrc:

```
export LD_LIBRARY_PATH=/usr/local/lib
```

However I've worked out what my problem is. I have to run python with sudo otherwise I get 

```
libsoc-file-debug: Permission denied
```

As sudo I don't have  LD_LIBRARY_PATH set.
After reading the following:
http://stackoverflow.com/questions/7880454/python-executable-not-finding-libpython-shared-library
I concluded that I needed to do a system wide setting by modifying /etc/ld.so.conf. Once this change was made all worked correctly.

Thanks,
Barry
